# Gradle

# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: Gradle@2
    displayName: gradlew build
    inputs:
      wrapperScript: 'gradlew'
      tasks: 'build'
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    condition: succeededOrFailed()
    inputs:
      SourceFolder: $(system.defaultworkingdirectory)
      Contents: '**/*.jar'
      TargetFolder: $(build.artifactstagingdirectory)
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: drop'
    condition: succeededOrFailed()
    inputs:
      PathtoPublish: $(build.artifactstagingdirectory)

  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: |
        Write-Host "$(Build.BuildNumber)"
        Write-Host "$(Build.DefinitionName)"
        Write-Host "$(SourceBranchName)"
        Write-Host "$(Date:yyyyMMdd)"

